test:
	NODE_ENV=test \
	SAUCE_ACCESS_KEY=my-sauce-key \
    SAUCE_USERNAME=my-sauce-username \
	SHERLOCKED_API=http://localhost:1077/api/ \
    TRAVIS_BRANCH=updateHat \
    TRAVIS_BUILD_ID=1234 \
    TRAVIS_COMMIT=211B \
    TRAVIS_JOB_NUMBER=211 \
    TRAVIS_PULL_REQUEST=1001 \
    TRAVIS_REPO_SLUG=ngokevin/sherlocked \
    node_modules/.bin/mocha test.js
